### ISSUE TITLE
All Aliyun proxies show up as "launching"

### ISSUE THREAD

**Issue by aranhoide** [getlantern/ops-panel#22] opened 2017-01-19 16:45 UTC
They should all be pro or retired at this point.

**Comment by oxtoacart** [comment] 2017-01-23 22:39
Related to getlantern/lantern-internal#638.

**Comment by oxtoacart** [comment] 2017-01-23 22:40
Duplicate of getlantern/lantern-internal#638.

**Closed by oxtoacart** 2017-01-23 22:40 UTC
